# Setup
title: ë°•í˜„ìƒ, HyunSang Park
description: "ì•ˆë…•í•˜ì„¸ìš”. ë°•í˜„ìƒì…ë‹ˆë‹¤.<br/>ì½ê³  ë“£ê³  ë§í•˜ê³  ì“°ê³ ë¥¼ ì˜í•˜ê³ ì ë…¸ë ¥í•˜ê³  ìˆìŠµë‹ˆë‹¤.<br/>ë‹¤ì–‘í•œ ë¶„ë“¤ê³¼ ê³µë™ì˜ ëª©í‘œë¥¼ ì„±ì·¨í•˜ê¸° ìœ„í•´ì„œ ë‹¤ì–‘í•œ í™œë™ì„ í•˜ê³  ìˆìŠµë‹ˆë‹¤."
url: "https://hyunsang.dev"
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  
author:
  name: ë°•í˜„ìƒ, HyunSang Park
  url: https://github.com/dev-hyunsang
  email: me@hyunsang.dev

# Navbar page list
nav:
  - title: About ğŸ§‘ğŸ»â€ğŸ’»
    url: /about
  - title: Hacking ğŸ› 
    url: /hacking
  - title: TIL ğŸ“š
    url: /TIL